apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-user
spec:
  selector:
    matchLabels:
      run: backend-user
  replicas: 2
  template:
    metadata:
      labels:
        run: backend-user
    spec:
      containers:
        - name: backend-user
          image: docker.io/peggylicious/udagram-api-user:v4
          ports:
            - containerPort: 8080
          envFrom: 
            - configMapRef:
                name: env-config
            - secretRef:
                name: env-secret
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 200m
          volumeMounts:
            - name: aws-configmap
              mountPath: "/root/.aws/"
      volumes:
        - name: aws-configmap
          configMap:
            name: aws-configmap
          
